use std::path::{Path, PathBuf};
use std::sync::Arc;

use arc_swap::ArcSwap;

use super::{
    BrowserConfig, ChannelConfig, CoalesceConfig, CompactionConfig, Config, CortexConfig,
    DefaultsConfig, IngestionConfig, McpServerConfig, MemoryPersistenceConfig, OpenCodeConfig,
    ResolvedAgentConfig, WarmupConfig, WarmupStatus, WorkReadiness, evaluate_work_readiness,
};
use crate::llm::routing::RoutingConfig;
use crate::tools::browser::SharedBrowserHandle;

/// Live configuration that can be hot-reloaded without restarting.
///
/// All fields use ArcSwap for lock-free reads. Consumers call `.load()` on
/// individual fields to get a snapshot — cheap and contention-free.
/// The file watcher calls `.store()` to atomically swap in new values.
pub struct RuntimeConfig {
    /// Instance root directory (e.g., ~/.spacebot). Immutable after startup.
    pub instance_dir: PathBuf,
    /// Agent workspace directory (e.g., ~/.spacebot/agents/{id}/workspace). Immutable after startup.
    pub workspace_dir: PathBuf,
    pub routing: ArcSwap<RoutingConfig>,
    pub compaction: ArcSwap<CompactionConfig>,
    pub memory_persistence: ArcSwap<MemoryPersistenceConfig>,
    pub coalesce: ArcSwap<CoalesceConfig>,
    pub ingestion: ArcSwap<IngestionConfig>,
    pub channel_config: ArcSwap<ChannelConfig>,
    pub max_turns: ArcSwap<usize>,
    pub branch_max_turns: ArcSwap<usize>,
    pub context_window: ArcSwap<usize>,
    pub max_concurrent_branches: ArcSwap<usize>,
    pub max_concurrent_workers: ArcSwap<usize>,
    pub browser_config: ArcSwap<BrowserConfig>,
    pub mcp: ArcSwap<Vec<McpServerConfig>>,
    pub history_backfill_count: ArcSwap<usize>,
    pub brave_search_key: ArcSwap<Option<String>>,
    pub cron_timezone: ArcSwap<Option<String>>,
    pub user_timezone: ArcSwap<Option<String>>,
    pub cortex: ArcSwap<CortexConfig>,
    pub warmup: ArcSwap<WarmupConfig>,
    /// Current warmup lifecycle status for API and observability.
    pub warmup_status: ArcSwap<WarmupStatus>,
    /// Synchronizes warmup passes so periodic and API-triggered runs don't overlap.
    pub warmup_lock: Arc<tokio::sync::Mutex<()>>,
    /// Cached memory bulletin generated by the cortex. Injected into every
    /// channel's system prompt. Empty string until the first cortex run.
    pub memory_bulletin: ArcSwap<String>,
    pub prompts: ArcSwap<crate::prompts::PromptEngine>,
    pub identity: ArcSwap<crate::identity::Identity>,
    pub skills: ArcSwap<crate::skills::SkillSet>,
    pub opencode: ArcSwap<OpenCodeConfig>,
    /// Shared pool of OpenCode server processes. Lazily initialized on first use.
    pub opencode_server_pool: ArcSwap<crate::opencode::OpenCodeServerPool>,
    /// Cron store, set after agent initialization.
    pub cron_store: ArcSwap<Option<Arc<crate::cron::CronStore>>>,
    /// Cron scheduler, set after agent initialization.
    pub cron_scheduler: ArcSwap<Option<Arc<crate::cron::Scheduler>>>,
    /// Settings store for agent-specific configuration.
    pub settings: ArcSwap<Option<Arc<crate::settings::SettingsStore>>>,
    /// Tracks whether listen_only_mode is explicitly configured via agent/env.
    /// When set, channel-local persisted values must not override it.
    pub channel_listen_only_explicit: ArcSwap<Option<bool>>,
    /// Secrets store for encrypted credential storage.
    pub secrets: ArcSwap<Option<Arc<crate::secrets::store::SecretsStore>>>,
    /// Sandbox configuration for process containment.
    ///
    /// Wrapped in `Arc` so it can be shared with the `Sandbox` struct, which
    /// reads the current mode dynamically on every `wrap()` call.
    pub sandbox: Arc<ArcSwap<crate::sandbox::SandboxConfig>>,
    /// Shared browser state for persistent sessions.
    ///
    /// When `browser.persist_session = true`, all workers share this handle so
    /// the browser process and tabs survive across worker lifetimes. When
    /// `persist_session = false` this is `None` and each worker creates its own.
    pub shared_browser: Option<SharedBrowserHandle>,
}

impl RuntimeConfig {
    /// Build from a resolved agent config, loaded prompts, identity, and skills.
    pub fn new(
        instance_dir: &Path,
        agent_config: &ResolvedAgentConfig,
        defaults: &DefaultsConfig,
        prompts: crate::prompts::PromptEngine,
        identity: crate::identity::Identity,
        skills: crate::skills::SkillSet,
    ) -> Self {
        let opencode_config = &defaults.opencode;
        let server_pool = crate::opencode::OpenCodeServerPool::new(
            opencode_config.path.clone(),
            opencode_config.permissions.clone(),
            opencode_config.max_servers,
        );

        Self {
            instance_dir: instance_dir.to_path_buf(),
            workspace_dir: agent_config.workspace.clone(),
            routing: ArcSwap::from_pointee(agent_config.routing.clone()),
            compaction: ArcSwap::from_pointee(agent_config.compaction),
            memory_persistence: ArcSwap::from_pointee(agent_config.memory_persistence),
            coalesce: ArcSwap::from_pointee(agent_config.coalesce),
            ingestion: ArcSwap::from_pointee(agent_config.ingestion),
            channel_config: ArcSwap::from_pointee(agent_config.channel),
            max_turns: ArcSwap::from_pointee(agent_config.max_turns),
            branch_max_turns: ArcSwap::from_pointee(agent_config.branch_max_turns),
            context_window: ArcSwap::from_pointee(agent_config.context_window),
            max_concurrent_branches: ArcSwap::from_pointee(agent_config.max_concurrent_branches),
            max_concurrent_workers: ArcSwap::from_pointee(agent_config.max_concurrent_workers),
            browser_config: ArcSwap::from_pointee(agent_config.browser.clone()),
            mcp: ArcSwap::from_pointee(agent_config.mcp.clone()),
            history_backfill_count: ArcSwap::from_pointee(agent_config.history_backfill_count),
            brave_search_key: ArcSwap::from_pointee(agent_config.brave_search_key.clone()),
            cron_timezone: ArcSwap::from_pointee(agent_config.cron_timezone.clone()),
            user_timezone: ArcSwap::from_pointee(agent_config.user_timezone.clone()),
            cortex: ArcSwap::from_pointee(agent_config.cortex),
            warmup: ArcSwap::from_pointee(agent_config.warmup),
            warmup_status: ArcSwap::from_pointee(WarmupStatus::default()),
            warmup_lock: Arc::new(tokio::sync::Mutex::new(())),
            memory_bulletin: ArcSwap::from_pointee(String::new()),
            prompts: ArcSwap::from_pointee(prompts),
            identity: ArcSwap::from_pointee(identity),
            skills: ArcSwap::from_pointee(skills),
            opencode: ArcSwap::from_pointee(defaults.opencode.clone()),
            opencode_server_pool: ArcSwap::from_pointee(server_pool),
            cron_store: ArcSwap::from_pointee(None),
            cron_scheduler: ArcSwap::from_pointee(None),
            settings: ArcSwap::from_pointee(None),
            channel_listen_only_explicit: ArcSwap::from_pointee(None),
            secrets: ArcSwap::from_pointee(None),
            sandbox: Arc::new(ArcSwap::from_pointee(agent_config.sandbox.clone())),
            shared_browser: if agent_config.browser.persist_session {
                Some(crate::tools::browser::new_shared_browser_handle())
            } else {
                None
            },
        }
    }

    /// Set the cron store and scheduler after initialization.
    pub fn set_cron(
        &self,
        store: Arc<crate::cron::CronStore>,
        scheduler: Arc<crate::cron::Scheduler>,
    ) {
        self.cron_store.store(Arc::new(Some(store)));
        self.cron_scheduler.store(Arc::new(Some(scheduler)));
    }

    /// Set the settings store after initialization.
    pub fn set_settings(
        &self,
        settings: Arc<crate::settings::SettingsStore>,
        explicit_listen_only: Option<bool>,
    ) {
        self.settings.store(Arc::new(Some(settings.clone())));
        self.channel_listen_only_explicit
            .store(Arc::new(explicit_listen_only));
        if explicit_listen_only.is_none() {
            match settings.channel_listen_only_mode() {
                Ok(Some(enabled)) => {
                    self.channel_config.rcu(move |current| {
                        let mut next = **current;
                        next.listen_only_mode = enabled;
                        Arc::new(next)
                    });
                }
                Ok(None) => {}
                Err(error) => {
                    tracing::warn!(%error, "failed to load persisted channel listen_only_mode");
                }
            }
        }
    }

    /// Set the secrets store after initialization.
    pub fn set_secrets(&self, secrets: Arc<crate::secrets::store::SecretsStore>) {
        self.secrets.store(Arc::new(Some(secrets)));
    }

    /// Compute the current dispatch-readiness signal.
    pub fn work_readiness(&self) -> WorkReadiness {
        let warmup_config = **self.warmup.load();
        let status = self.warmup_status.load().as_ref().clone();
        evaluate_work_readiness(warmup_config, status, chrono::Utc::now().timestamp_millis())
    }

    /// True when branch/worker/cron dispatches should run in fully-ready mode.
    pub fn ready_for_work(&self) -> bool {
        self.work_readiness().ready
    }

    /// Path to the saved attachments directory for persisted channel files.
    pub fn saved_dir(&self) -> std::path::PathBuf {
        self.workspace_dir.join("saved")
    }

    /// Reload tunable config values from a freshly parsed Config.
    ///
    /// Finds the matching agent by ID, re-resolves it against defaults, and
    /// swaps all reloadable fields. Does not handle API keys (those are
    /// reloaded via LlmManager), DB paths, messaging adapters, or agent
    /// topology.
    pub async fn reload_config(
        &self,
        config: &Config,
        agent_id: &str,
        mcp_manager: &crate::mcp::McpManager,
    ) {
        let agent = config.agents.iter().find(|a| a.id == agent_id);
        let Some(agent) = agent else {
            tracing::warn!(agent_id, "agent not found in reloaded config, skipping");
            return;
        };

        let resolved = agent.resolve(&config.instance_dir, &config.defaults);
        let old_mcp = (**self.mcp.load()).clone();
        let new_mcp = resolved.mcp.clone();

        self.routing.store(Arc::new(resolved.routing));
        self.compaction.store(Arc::new(resolved.compaction));
        self.memory_persistence
            .store(Arc::new(resolved.memory_persistence));
        self.coalesce.store(Arc::new(resolved.coalesce));
        self.ingestion.store(Arc::new(resolved.ingestion));
        let resolved_channel = resolved.channel;
        let configured_listen_only = agent.channel.map(|channel| channel.listen_only_mode);
        self.channel_listen_only_explicit
            .store(Arc::new(configured_listen_only));
        let persisted_listen_only = self.settings.load().as_ref().as_ref().and_then(|settings| {
            match settings.channel_listen_only_mode() {
                Ok(value) => value,
                Err(error) => {
                    tracing::warn!(
                        %error,
                        "failed to load persisted channel listen_only_mode during reload"
                    );
                    None
                }
            }
        });
        self.channel_config.rcu(move |current| {
            let mut next = resolved_channel;
            next.listen_only_mode = configured_listen_only
                .or(persisted_listen_only)
                .unwrap_or(current.as_ref().listen_only_mode);
            // save_attachments has no persisted override — config is authoritative
            Arc::new(next)
        });
        self.max_turns.store(Arc::new(resolved.max_turns));
        self.branch_max_turns
            .store(Arc::new(resolved.branch_max_turns));
        self.context_window.store(Arc::new(resolved.context_window));
        self.max_concurrent_branches
            .store(Arc::new(resolved.max_concurrent_branches));
        self.max_concurrent_workers
            .store(Arc::new(resolved.max_concurrent_workers));
        let old_persist = self.browser_config.load().persist_session;
        let new_persist = resolved.browser.persist_session;
        if old_persist != new_persist {
            tracing::warn!(
                agent_id,
                old = old_persist,
                new = new_persist,
                "persist_session changed — restart the agent for this to take effect"
            );
        }
        self.browser_config.store(Arc::new(resolved.browser));
        self.mcp.store(Arc::new(new_mcp.clone()));
        self.history_backfill_count
            .store(Arc::new(resolved.history_backfill_count));
        self.brave_search_key
            .store(Arc::new(resolved.brave_search_key));
        self.cron_timezone.store(Arc::new(resolved.cron_timezone));
        self.user_timezone.store(Arc::new(resolved.user_timezone));
        self.cortex.store(Arc::new(resolved.cortex));
        self.warmup.store(Arc::new(resolved.warmup));
        self.sandbox.store(Arc::new(resolved.sandbox.clone()));

        let old_opencode = self.opencode.load().as_ref().clone();
        let new_opencode = config.defaults.opencode.clone();
        self.opencode.store(Arc::new(new_opencode.clone()));

        let should_rebuild_opencode_pool = old_opencode.path != new_opencode.path
            || old_opencode.max_servers != new_opencode.max_servers
            || old_opencode.permissions != new_opencode.permissions;
        if should_rebuild_opencode_pool {
            let new_pool = crate::opencode::OpenCodeServerPool::new(
                new_opencode.path.clone(),
                new_opencode.permissions.clone(),
                new_opencode.max_servers,
            );
            self.opencode_server_pool.store(Arc::new(new_pool));
            tracing::info!(
                agent_id,
                "reloaded opencode server pool with updated path/permissions/limits"
            );
        }

        mcp_manager.reconcile(&old_mcp, &new_mcp).await;

        tracing::info!(agent_id, "runtime config reloaded");
    }

    /// Reload identity files from disk.
    pub fn reload_identity(&self, identity: crate::identity::Identity) {
        self.identity.store(Arc::new(identity));
        tracing::info!("identity reloaded");
    }

    /// Reload skills from disk.
    pub fn reload_skills(&self, skills: crate::skills::SkillSet) {
        self.skills.store(Arc::new(skills));
        tracing::info!("skills reloaded");
    }
}

impl std::fmt::Debug for RuntimeConfig {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("RuntimeConfig").finish_non_exhaustive()
    }
}
